export const featured = [
    {
        id: 1,
        propertiFor: "For sell",
        img: "/images/flat.png",
        flatName: "103/143 West Street,  Crows Nest",
        location: "Raipur, Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 52364",
        realPrice: "₹ 200000",
    },
    {
        id: 2,
        propertiFor: "For sell",
        img: "/images/secondbuilding.png",
        flatName: "103/143 West Street,  Crows Nest",
        location: "korba, Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 75982",
        realPrice: "₹ 200000",
    },
    {
        id: 3,
        propertiFor: "For sell",
        img: "/images/flat.png",
        flatName: "103/143 West Street,  Crows Nest",
        location: "korba, Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 52364",
        realPrice: "₹ 200000",
    },

    {
        id: 3,
        propertiFor: "For sell",
        img: "/images/secondbuilding.png",
        flatName: "103/143 West Street,  Crows Nest",
        location: "Raipur, Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 52364",
        realPrice: "₹ 200000",
    },
];