const propertydb = [
    {
        id: 1,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
    
      },
      {
        id: 2,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
    
      },
      {
        id: 3,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 4,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 5,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 6,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 7,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 8,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 9,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 10,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 11,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 12,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 13,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 14,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 15,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 16,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 17,
        propertiFor: "For Sell",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 18,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 19,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      },
      {
        id: 20,
        propertiFor: "For Rent",
        img: "/images/CardImg.png",
        flatName: "Beach Villa",
        location: "Korba Chhattisgrah",
        bed: "2 Beds",
        bath: "1 Bath",
        flatSize: "1200 Sq ft",
        price: "₹ 120000",
      }
]

export default propertydb;