import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import styles from "../styles/Home.module.css";
// import * from "react-icons";
import Home from "./home";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PARIDHI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/paridhiFavicon.ico" />
      </Head>
      <div>
        <Home />
      </div>
    </div>
  );
}